# Generated by Django 3.1.5 on 2021-03-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0002_auto_20210311_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='services',
            field=models.CharField(choices=[('cardilogie', 'cardilogie'), ('biologie', 'biologie'), ('radiologie', 'radiologie'), ('chirurgie', 'chirurgie'), ('pneumologie', 'pneumologie'), ('dermatologie', 'dermatologie'), ('Pédiatrie', 'Pédiatrie'), ('traumatologie', 'traumatologie'), ('pneumologie', 'pneumologie'), ("service d'accueil de traitement des urgences", "service d'accueil de traitement des urgences")], max_length=300, null=True),
        ),
    ]
