# Generated by Django 3.1.5 on 2021-03-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0003_auto_20210311_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='services',
            field=models.CharField(choices=[('immunologie', 'immunologie'), ('cardiologie', 'cardiologie'), ('radiologie', 'radiologie'), ('chirurgie', 'chirurgie'), ('pneumologie', 'pneumologie'), ('dermatologie', 'dermatologie'), ('Pédiatrie', 'Pédiatrie'), ('traumatologie', 'traumatologie'), ('maternité', 'maternité'), ('pneumologie', 'pneumologie'), ("service d'accueil de traitement des urgences", "service d'accueil de traitement des urgences")], max_length=300, null=True),
        ),
    ]
