# Generated by Django 3.1.5 on 2021-03-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0006_auto_20210325_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Status',
            field=models.CharField(choices=[('Fait', 'Fait'), ('En cours', 'En cours')], max_length=300, null=True),
        ),
    ]
