# Generated by Django 3.1.5 on 2021-03-29 14:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0007_auto_20210327_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='codebr',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
