# Generated by Django 3.1.5 on 2021-04-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0008_auto_20210329_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
